<?php

use App\Models\GeneratedDocument;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Livewire\Component;

new #[Title('Document Verification')] #[Layout('layouts.guest')] class extends Component
{
    public string $number = '';

    public ?GeneratedDocument $document = null;

    public bool $isValid = false;

    public function mount(string $number): void
    {
        $decodedNumber = urldecode($number);
        $this->number = $decodedNumber;

        $this->document = GeneratedDocument::with([
            'placement.student',
            'placement.organization',
            'template',
        ])->where('document_number', $decodedNumber)->first();

        if ($this->document) {
            $this->isValid = true;
        }
    }
}; ?>

<div class="min-h-screen bg-zinc-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-md text-center">
        @if ($document?->placement?->student?->institution?->logo_url)
            <img src="{{ $document->placement->student->institution->logo_url }}" alt="Logo" class="mx-auto h-16 w-auto mb-4">
        @else
            <div class="mx-auto h-16 w-16 bg-zinc-800 rounded-full flex items-center justify-center mb-4 shadow-sm">
                <flux:icon.building-library class="size-8 text-white" />
            </div>
        @endif
        
        <h2 class="mt-2 text-center text-3xl font-extrabold text-zinc-900 uppercase tracking-tight">
            Document Verification
        </h2>
        <p class="mt-2 text-center text-sm text-zinc-600">
            Verify the authenticity of an electronically generated document.
        </p>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-xl">
        <div class="bg-white py-8 px-4 shadow sm:rounded-xl sm:px-10 border border-zinc-200">
            @if ($isValid && $document)
                <div class="flex flex-col items-center border-b border-zinc-100 pb-6 mb-6">
                    <div class="h-16 w-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
                        <flux:icon.check-badge class="size-10 text-green-600" />
                    </div>
                    <h3 class="text-xl font-bold text-green-700">Valid Document</h3>
                    <p class="text-sm text-zinc-500 mt-1">This document was officially generated by the system.</p>
                </div>

                <dl class="grid grid-cols-1 gap-y-4 sm:grid-cols-2">
                    <div class="sm:col-span-2">
                        <dt class="text-xs font-bold text-zinc-500 uppercase tracking-wider">Reference Number</dt>
                        <dd class="mt-1 text-sm text-zinc-900 font-mono bg-zinc-50 p-2 rounded border border-zinc-100 inline-block">
                            {{ $document->document_number }}
                        </dd>
                    </div>

                    <div class="sm:col-span-2">
                        <dt class="text-xs font-bold text-zinc-500 uppercase tracking-wider">Document Type</dt>
                        <dd class="mt-1 text-base font-semibold text-zinc-900">
                            {{ $document->template->title ?? 'Official Placement Letter' }}
                        </dd>
                    </div>

                    <div class="sm:col-span-1">
                        <dt class="text-xs font-bold text-zinc-500 uppercase tracking-wider">Issued To</dt>
                        <dd class="mt-1 text-sm text-zinc-900 font-medium">
                            {{ $document->placement->student->full_name ?? 'N/A' }}
                        </dd>
                        <dd class="text-xs text-zinc-500 mt-0.5">
                            {{ $document->placement->student->matric_number ?? '' }}
                        </dd>
                    </div>

                    <div class="sm:col-span-1">
                        <dt class="text-xs font-bold text-zinc-500 uppercase tracking-wider">Posted To</dt>
                        <dd class="mt-1 text-sm text-zinc-900 font-medium">
                            {{ $document->placement->organization_display_name ?? 'N/A' }}
                        </dd>
                    </div>

                    <div class="sm:col-span-2 mt-2 pt-4 border-t border-zinc-100">
                        <dt class="text-xs font-bold text-zinc-500 uppercase tracking-wider">Generation Date</dt>
                        <dd class="mt-1 text-sm text-zinc-900">
                            {{ $document->generated_at->format('l, F j, Y \a\t g:i A') }}
                        </dd>
                    </div>
                </dl>
                
                <div class="mt-8 flex justify-center">
                    <flux:button href="{{ route('cms.placements.print', ['doc' => $document->document_number]) }}" target="_blank" variant="primary" icon="document-text">
                        View Original Document
                    </flux:button>
                </div>
            @else
                <div class="flex flex-col items-center py-6">
                    <div class="h-16 w-16 bg-red-100 rounded-full flex items-center justify-center mb-4">
                        <flux:icon.x-circle class="size-10 text-red-600" />
                    </div>
                    <h3 class="text-xl font-bold text-red-700">Invalid Document</h3>
                    <p class="text-sm text-zinc-500 mt-2 text-center max-w-sm">
                        We could not find any official records matching the provided reference number. This document may be fraudulent or the reference number was mistyped.
                    </p>
                    
                    <div class="mt-6 w-full bg-red-50 border border-red-100 rounded-lg p-4 text-center">
                        <span class="text-xs font-bold text-red-800 uppercase tracking-wider block mb-1">Queried Reference:</span>
                        <span class="font-mono text-sm text-red-900">{{ $number }}</span>
                    </div>
                </div>
            @endif
        </div>
    </div>
    
    <div class="mt-8 text-center text-xs text-zinc-400">
        &copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.
    </div>
</div>
